import Head from "next/head";
import Navbar from "../Navbar/Navbar1";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Edge Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </>
  );
}
