import Head from 'next/head'
import Navbar from '../Navbar/Navbar1'

export default function Layout({ children, user, logout }) {
  return (
    <>
      <Head>
        <title>Edge Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar user={user} logout={logout} />
      <main>{children}</main>
    </>
  )
}
